version: '3'

services:
  core0:
    container_name: core0
    image: "ghcr.io/celestiaorg/celestia-app@sha256:9166143fe2a6502a2e9edad84db4973ae1a06f044faa5dee9d20190f33906671"
    entrypoint: [
      "/bin/bash"
    ]
    command: [
      "/start-celestia-appd.sh"
    ]
    volumes:
      - ${PWD}/docker/start-celestia-appd.sh:/start-celestia-appd.sh:ro
      - ${PWD}/docker/fix-genesis.sh:/fix-genesis.sh:ro
      - keyring-volume:/celestia-app/node/keyring-test
    networks:
      localnet:
        ipv4_address: 192.167.10.10

  bridge0:
    container_name: bridge0
    depends_on:
      - core0
    image: "ghcr.io/celestiaorg/celestia-node:sha-25652db"
    entrypoint: [
      "/bin/bash"
    ]
    command: [
      "/start-bridge.sh"
    ]
    volumes:
      - ${PWD}/docker/wait-for-it.sh:/wait-for-it.sh:ro
      - ${PWD}/docker/start-bridge.sh:/start-bridge.sh:ro
      - keyring-volume:/bridge/keys/keyring-test/:ro

    expose:
      - "26658/tcp"

    ports:
      - "26658:26658"

    networks:
      localnet:
        ipv4_address: 192.167.10.20

volumes:
  keyring-volume:

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/24
